---

- name: install postgresql
  yay:
    name: postgresql
    state: present
    update_cache: true

- name: Postgresql database directory
  debug:
    msg: "PostgreSQL data dir : {{ postgresql_pgdata }}"


- name: init data directory if needed
  become_user: postgres
  become: true
  shell: "initdb -D {{ postgresql_pgdata }}"
  args:
    creates: "{{ postgresql_pgdata }}/PG_VERSION"

- name: Enable and start PostgreSQL service
  become: true
  systemd:
    name: postgresql
    enabled: true
    state: started

- name: allow connection from local network
  become: true
  lineinfile:
    path: "{{ postgresql_pgdata }}/pg_hba.conf"
    line: "host all  all  {{ postgresql_allowed_network }}  trust"
    insertafter: EOF
    state: present
  notify: Restart PostgreSQL
  when: postgresql_allowed_network is defined

- name: remove rights if no network defined
  become: true
  lineinfile:
    path: "{{ postgresql_pgdata }}/pg_hba.conf"
    regexp: '^host.*/24.*trust'
    state: absent
  notify: Restart PostgreSQL
  when: postgresql_allowed_network is not defined

- name: listen on all provided interfaces
  become: true
  lineinfile:
    path: "{{ postgresql_pgdata }}/postgresql.conf"
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '{{ postgresql_listen_addresses }}'"
    state: present
  notify: Restart PostgreSQL

