#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/yay

- name: check if yay is already installed
  ansible.builtin.stat:
    path: /usr/bin/yay
  register: yay
 
- name: Install it if not
  ansible.builtin.include_tasks: installYay.yml
  when: not yay.stat.exists
