---

- name: create remote user
  ansible.builtin.user:
    name: "{{ deployer_user }}"
    create_home: true

- name: copier la clef
  ansible.builtin.authorized_key:
    user: "{{ deployer_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: add sudo right
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ deployer_user }}"
    line: "{{ deployer_user }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    create: yes
    validate: '/usr/sbin/visudo -cf %s'
