- name: Build core system
  hosts: buildSys
  vars:
    # As the dedicated user doesn't exist yet, we need to use root
    ansible_user: root

  roles:
    - name: Update_pacman	# Yay is not yet installed
    - name: hostname
    - name: timezone
    - name: locale
    - name: reflector
    - name: buildsys_complements
    - name: environment
    - name: avahi
    - name: yay
