- name: Build core system
  hosts: buildSys
  vars:
    # As the dedicated user doesn't exist yet, we need to use root
    ansible_user: root
    ansible_roles_path:
      - ./buildSys

  roles:
    - name: buildSys.Update_pacman	# Update packages repository, Yay is not yet installed
    - name: buildSys.hostname      # set the hostname
    - name: buildSys.timezone      # set our timezone
    - name: buildSys.locale        # set our locales
    - name: buildSys.reflector     # speedup next deployment
    - name: buildSys.buildsys_complements  # install additional packages
    - name: buildSys.environment   # setup environment variables / alias
    - name: buildSys.avahi         # Install and enable avahi
    - name: buildSys.yay           # install yay
    - name: buildSys.deployer      # install ansible user
    - name: buildSys.users         # create additional users
    - name: buildSys.disableRoot   # Disable root login
