# Hosts definition

# x86 POC/Crash machines
x86:
  hosts:
    poc:
      ansible_host: 192.168.0.34
      ansible_user: ansible

######
# Stages
######

# Build core systems
buildSys:
  hosts:
    poc
