# Hosts definition

# x86 POC/Crash machines
x86:
  hosts:
    poc:
      ansible_host: 192.168.0.28
      ansible_user: deployer

# ARM SBCs
arm: 
  hosts: {}

######
# Stages
######

# Build core systems (one shot)
buildSys:
  hosts:
    poc

# Everything needed for system maintenance (idempotent)
finalizeSys:
  hosts:
    poc

# Recurent system maintenance (backup excluded)
maintainSys:
  hosts:
    poc

# Need my very own tools
destroyedlolo:
  hosts:
    poc

# Install smart homing tools
SmartHome:
  hosts:
    poc
