# Hosts definition

# x86 POC/Crash machines
x86:
  hosts:
    poc:
      ansible_host: 192.168.0.34
      ansible_user: deployer

######
# Stages
######

# Build core systems (one shot)
buildSys:
  hosts:
    poc

# Everything needed for system maintenance (idempotent)
finalizeSys:
  hosts:
    poc

# Recurent system maintenance (backup excluded)
maintainSys:
  hosts:
    poc

# Need you very own tools
Laurent:
  hosts:
    poc

