- name: Finalize system installation
  hosts: finalizeSys

  roles:
    - name: packages_install    # update installed packages
    - role: Laurent.LFMakeMaker # Make helper
      when: "'Laurent' in group_names"
    - role: Laurent.PubSysFigures
      when: "'Laurent' in group_names"
