---

- name: Display timezone
  debug:
    var: new_timezone

- name: set timezone
  community.general.timezone:
    name: "{{ new_timezone }}"

- name: ensure the time synchronisation is running
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: systemd-timesyncd
