---

- name: Clone the repository
  git:
    repo: https://github.com/destroyedlolo/Marcel.git
    dest: "/tmp/Marcel"
    force: true

- name: comments out all options
  replace:
    path: "/tmp/Marcel/remake.sh"
    regexp: '^(\s*BUILD_.*)$'
    replace: '# \1'

- name: activate requested ones
  replace:
    path: "/tmp/Marcel/remake.sh"
    regexp: '^#\s*(BUILD_{{ item }}.*)$'
    replace: '\1'
  loop: '{{ Marcel_modules }}'

- name: rebuild the Makefile
  command: sh remake.sh
  args:
    chdir: /tmp/Marcel

- name: Compile Marcel
  command: make -j
  args:
    chdir: /tmp/Marcel


- name: create target directory if needed
  become: yes
  file:
    path: /usr/local/lib/Marcel
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'

- name: Install Marcel
  become: yes
  command: sh install.sh
  args:
    chdir: /tmp/Marcel
    creates: /usr/local/lib/Marcel/mod_1wire.so

- name: cleaning
  file:
    path: /tmp/Marcel
    state: absent

