---

- name: Install avahi
  ansible.builtin.package:
    name: "avahi"
    state: present

- name: Install nss-mdns
  ansible.builtin.package:
    name: "nss-mdns"
    state: present

- name: configure nsswitch
  ansible.builtin.lineinfile:
    path: "/etc/nsswitch.conf"
    regexp: "^hosts:.*$"
    line: "hosts: mymachines mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns"
    backrefs: yes

- name: disable ipv6 advertising to avoid name's enumeration
  lineinfile:
    path: '/etc/avahi/avahi-daemon.conf'
    regexp: '^\s*#?\s*publish-a-on-ipv6='
    line: 'publish-a-on-ipv6=no'
    insertafter: '^\[server\]'
    create: no

- name: disable ipv6 at all
  lineinfile:
    path: '/etc/avahi/avahi-daemon.conf'
    regexp: '^\s*#?\s*use-ipv6='
    line: 'use-ipv6=no'
    insertafter: '^\[publish\]'
    create: no
    
- name: copy services
  shell: cp /usr/share/doc/avahi/*.service /etc/avahi/services/

- name: enable and start avahi
  ansible.builtin.systemd_service:
    name: "avahi-daemon.service"
    state: started
    enabled: true

- name: disable systemd-resolved
  ansible.builtin.systemd_service:
    name: "systemd-resolved"
    state: stopped
    enabled: false
