- name: Get the installed rock version
  shell: >
    luarocks show {{ item }} 2>/dev/null | awk '/^{{ item }}/ { print $2 }'
  register: installed_version
  changed_when: false
  failed_when: false

- name: Get the latest version available
  shell: >
    luarocks search --porcelain ansicolors | awk 'NR==1{ print $2 }'
  register: available_version
  changed_when: false

- name: Install or update luarocks module if needed
  command: "luarocks install {{ item }}"
  become: yes
  when: installed_version.stdout != available_version.stdout
